# Run Google Tests (via CTest) using "GitHub Actions" CI
# Adapted from the default template, as well as https://github.com/GHF/googletest-ci (CC license)

name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Configure CMake
        run: cmake -S $GITHUB_WORKSPACE -B ${{runner.workspace}}/build

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: cmake --build .

      - name: Test
        working-directory: ${{runner.workspace}}/build
        run: GTEST_OUTPUT=xml:test-results/ GTEST_COLOR=1 ctest -V
        
      - name: print tree for testing CI
        working-directory: ${{runner.workspace}}/build
        run: tree

      - name: Generate code coverage
        working-directory: ${{runner.workspace}}/build-coverage
        run: |
          cmake -S $GITHUB_WORKSPACE -B ${{runner.workspace}}/build-coverage \
                -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=--coverage -DCMAKE_C_FLAGS=--coverage
          cmake --build .
          ctest -V
          ls -a

      - Generate Lcov report
        uses: daalbano/lcov-action@v1
        with:
          remove_patterns: 3rdparties,benchmarks

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test_results_xml
          path: ${{runner.workspace}}/build/tests/test-results/**/*.xml
